### ISSUE TITLE
correct answer

### ISSUE THREAD

**Issue by jabranham** [jabranham/canvasR#1]
Should provide the option to have the exported data.frame include info as to which answer is correct

**Comment by bapfeld** [comment]
Figured out how to pull the response IDs and identify the correct answer based on that for questions with and without feedback. How do you think we should include that information in the output? 
We could copy the correct answer text a second time into a column identified that way, or we could identify which column is supposed to contain the correct answer. I could also imagine an option in the function to reorder the answers so that the correct answer is always listed first.

**Comment by jabranham** [comment]
Neato. Here's what I think we should do:
1. make this a package - I've already done this. Take a look at the PR and see what you think? Need to work on documentation/examples a bit but I think everything works. The example quiz you included on your PR yesterday is in the data/ folder. 
2. write a function that pulls out the correct answer. Sounds like you already did this. Put it in the R/ folder? 
3. Allow an option in the import_quiz function to include the correct answer in a separate column

What do you think?
